export { default as whiteLogo } from "./white-logo.svg"
export { default as heroImage } from "./hero-image.jpg"
export { default as noise } from "./noise.png"
export { default as blackLogo } from "./black-logo.svg"
export { default as aboutImage } from "./about-image.jpg"
